apiVersion: v1
kind: Service

metadata:
  name: kubernetes-webapp-service

spec:
  selector:
    app: kubernetes-webapp

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: NodePort